// Seed script for courses — uses pg directly to avoid ESM workspace issues
// Run: pnpm --filter=web seed:courses

// eslint-disable-next-line @typescript-eslint/no-require-imports
require("/Users/abubaker/projects/graduate-dev/packages/db/node_modules/dotenv").config({ path: "/Users/abubaker/projects/graduate-dev/apps/web/.env.local" });

// eslint-disable-next-line @typescript-eslint/no-require-imports
const { Pool } = require("/Users/abubaker/projects/graduate-dev/packages/db/node_modules/pg");
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { randomUUID } = require("crypto");

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) { console.error("DATABASE_URL not set"); process.exit(1); }

function normUrl(url: string): string {
  const u = new URL(url);
  if (u.searchParams.get("sslmode") && u.searchParams.get("uselibpqcompat") !== "true") {
    u.searchParams.set("uselibpqcompat", "true");
  }
  return u.toString();
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const pool = new Pool({ connectionString: normUrl(DATABASE_URL!), max: 3 }) as any;

type Course = {
  slug: string; title: string; description: string; provider: string;
  imageUrl: string | null; courseUrl: string; level: string; category: string;
  tags: string[]; durationHours: number | null; studentCount: number | null;
  rating: number | null; isFree: boolean; isPublished: boolean; order: number;
};

const COURSES: Course[] = [
  {
    slug: "cs50-introduction",
    title: "CS50's Introduction to Computer Science",
    description: "Harvard's legendary introduction to CS covering fundamentals from web design to AI.",
    provider: "Harvard/edX",
    imageUrl: null,
    courseUrl: "https://cs50.harvard.edu/x/",
    level: "beginner",
    category: "CS Fundamentals",
    tags: ["C", "Python", "SQL", "Fundamentals"],
    durationHours: null,
    studentCount: 4000000,
    rating: 4.9,
    isFree: true,
    isPublished: true,
    order: 1,
  },
  {
    slug: "cs50-python",
    title: "CS50's Introduction to Programming with Python",
    description: "Learn Python programming from Harvard with clear explanations and modern practices.",
    provider: "Harvard/edX",
    imageUrl: null,
    courseUrl: "https://cs50.harvard.edu/python/",
    level: "beginner",
    category: "CS Fundamentals",
    tags: ["Python", "Programming"],
    durationHours: null,
    studentCount: 1000000,
    rating: 4.9,
    isFree: true,
    isPublished: true,
    order: 2,
  },
  {
    slug: "cs50-ai",
    title: "CS50's Introduction to AI with Python",
    description: "Explore AI, machine learning, and neural networks with Harvard's practical approach.",
    provider: "Harvard/edX",
    imageUrl: null,
    courseUrl: "https://cs50.harvard.edu/ai/",
    level: "intermediate",
    category: "AI/ML",
    tags: ["AI", "Machine Learning", "Python"],
    durationHours: null,
    studentCount: 500000,
    rating: 4.8,
    isFree: true,
    isPublished: true,
    order: 3,
  },
  {
    slug: "cs50-web",
    title: "CS50's Web Programming with Python and JavaScript",
    description: "Build full-stack web applications using Python, Django, JavaScript, and React.",
    provider: "Harvard/edX",
    imageUrl: null,
    courseUrl: "https://cs50.harvard.edu/web/",
    level: "intermediate",
    category: "Web Dev",
    tags: ["Python", "Django", "JavaScript", "React"],
    durationHours: null,
    studentCount: 600000,
    rating: 4.8,
    isFree: true,
    isPublished: true,
    order: 4,
  },
  {
    slug: "freecodecamp-responsive-web",
    title: "Responsive Web Design Certification",
    description: "Master HTML, CSS, and responsive design through hands-on projects.",
    provider: "freeCodeCamp",
    imageUrl: null,
    courseUrl: "https://www.freecodecamp.org/learn/2022/responsive-web-design/",
    level: "beginner",
    category: "Web Dev",
    tags: ["HTML", "CSS", "Responsive Design"],
    durationHours: 300,
    studentCount: 10000000,
    rating: 4.7,
    isFree: true,
    isPublished: true,
    order: 5,
  },
  {
    slug: "freecodecamp-javascript",
    title: "JavaScript Algorithms and Data Structures",
    description: "Learn JavaScript fundamentals and solve algorithmic challenges.",
    provider: "freeCodeCamp",
    imageUrl: null,
    courseUrl: "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/",
    level: "beginner",
    category: "CS Fundamentals",
    tags: ["JavaScript", "Algorithms", "Data Structures"],
    durationHours: 300,
    studentCount: 8000000,
    rating: 4.7,
    isFree: true,
    isPublished: true,
    order: 6,
  },
  {
    slug: "freecodecamp-python-data",
    title: "Scientific Computing with Python",
    description: "Learn NumPy, Pandas, and data analysis for scientific computing.",
    provider: "freeCodeCamp",
    imageUrl: null,
    courseUrl: "https://www.freecodecamp.org/learn/scientific-computing-with-python/",
    level: "beginner",
    category: "Data",
    tags: ["Python", "NumPy", "Pandas"],
    durationHours: 300,
    studentCount: 3000000,
    rating: 4.6,
    isFree: true,
    isPublished: true,
    order: 7,
  },
  {
    slug: "freecodecamp-relational-db",
    title: "Relational Database Certification",
    description: "Master SQL and database design with PostgreSQL and MySQL.",
    provider: "freeCodeCamp",
    imageUrl: null,
    courseUrl: "https://www.freecodecamp.org/learn/relational-database/",
    level: "beginner",
    category: "Backend",
    tags: ["SQL", "PostgreSQL", "Databases"],
    durationHours: 300,
    studentCount: 2000000,
    rating: 4.6,
    isFree: true,
    isPublished: true,
    order: 8,
  },
  {
    slug: "deeplearning-ml-specialization",
    title: "Machine Learning Specialization",
    description: "Andrew Ng's complete ML course covering supervised and unsupervised learning.",
    provider: "DeepLearning.AI",
    imageUrl: null,
    courseUrl: "https://www.coursera.org/specializations/machine-learning-introduction",
    level: "intermediate",
    category: "AI/ML",
    tags: ["Machine Learning", "Andrew Ng", "Statistics"],
    durationHours: 90,
    studentCount: 1500000,
    rating: 4.9,
    isFree: true,
    isPublished: true,
    order: 9,
  },
  {
    slug: "deeplearning-deep-learning",
    title: "Deep Learning Specialization",
    description: "Comprehensive course on neural networks, CNNs, RNNs, and modern architectures.",
    provider: "DeepLearning.AI",
    imageUrl: null,
    courseUrl: "https://www.coursera.org/specializations/deep-learning",
    level: "intermediate",
    category: "AI/ML",
    tags: ["Deep Learning", "Neural Networks", "TensorFlow"],
    durationHours: 125,
    studentCount: 800000,
    rating: 4.9,
    isFree: true,
    isPublished: true,
    order: 10,
  },
  {
    slug: "deeplearning-mlops",
    title: "MLOps Specialization",
    description: "Learn to deploy, monitor, and manage machine learning models in production.",
    provider: "DeepLearning.AI",
    imageUrl: null,
    courseUrl: "https://www.coursera.org/specializations/machine-learning-engineering-for-production-mlops",
    level: "advanced",
    category: "DevOps",
    tags: ["MLOps", "Machine Learning", "Deployment"],
    durationHours: 80,
    studentCount: 300000,
    rating: 4.8,
    isFree: true,
    isPublished: true,
    order: 11,
  },
  {
    slug: "deeplearning-llm-semantic-search",
    title: "Large Language Models with Semantic Search",
    description: "Build powerful LLM applications with embeddings and semantic search.",
    provider: "DeepLearning.AI",
    imageUrl: null,
    courseUrl: "https://www.deeplearning.ai/short-courses/large-language-models-semantic-search/",
    level: "intermediate",
    category: "AI/ML",
    tags: ["LLMs", "NLP", "Embeddings"],
    durationHours: 1,
    studentCount: 200000,
    rating: 4.7,
    isFree: true,
    isPublished: true,
    order: 12,
  },
  {
    slug: "google-data-analytics",
    title: "Google Data Analytics Professional Certificate",
    description: "Learn data analysis using spreadsheets, SQL, R, and Tableau.",
    provider: "Google/Coursera",
    imageUrl: null,
    courseUrl: "https://www.coursera.org/professional-certificates/google-data-analytics",
    level: "beginner",
    category: "Data",
    tags: ["Data Analysis", "SQL", "Tableau"],
    durationHours: 180,
    studentCount: 2000000,
    rating: 4.8,
    isFree: true,
    isPublished: true,
    order: 13,
  },
  {
    slug: "google-ux-design",
    title: "Google UX Design Professional Certificate",
    description: "Master user experience design, wireframing, and prototyping.",
    provider: "Google/Coursera",
    imageUrl: null,
    courseUrl: "https://www.coursera.org/professional-certificates/google-ux-design",
    level: "beginner",
    category: "Web Dev",
    tags: ["UX Design", "Figma", "User Research"],
    durationHours: 200,
    studentCount: 1000000,
    rating: 4.7,
    isFree: true,
    isPublished: true,
    order: 14,
  },
  {
    slug: "google-it-automation-python",
    title: "Google IT Automation with Python",
    description: "Learn Python for IT automation and system administration.",
    provider: "Google/Coursera",
    imageUrl: null,
    courseUrl: "https://www.coursera.org/professional-certificates/google-it-automation",
    level: "intermediate",
    category: "Backend",
    tags: ["Python", "Automation", "Linux"],
    durationHours: 120,
    studentCount: 700000,
    rating: 4.8,
    isFree: true,
    isPublished: true,
    order: 15,
  },
  {
    slug: "mit-ocw-intro-programming",
    title: "Introduction to Computer Science and Programming",
    description: "MIT's foundational CS course teaching problem-solving with Python.",
    provider: "MIT OpenCourseWare",
    imageUrl: null,
    courseUrl: "https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/",
    level: "beginner",
    category: "CS Fundamentals",
    tags: ["Python", "Problem Solving", "MIT"],
    durationHours: 30,
    studentCount: 500000,
    rating: 4.8,
    isFree: true,
    isPublished: true,
    order: 16,
  },
  {
    slug: "stanford-algorithms",
    title: "Algorithms Specialization",
    description: "Master algorithm design and analysis from Stanford University.",
    provider: "Stanford/Coursera",
    imageUrl: null,
    courseUrl: "https://www.coursera.org/specializations/algorithms",
    level: "intermediate",
    category: "CS Fundamentals",
    tags: ["Algorithms", "Data Structures", "Complexity"],
    durationHours: 80,
    studentCount: 700000,
    rating: 4.8,
    isFree: true,
    isPublished: true,
    order: 17,
  },
  {
    slug: "fullstackopen",
    title: "Full Stack Open",
    description: "Modern web development course teaching React, Node.js, and PostgreSQL.",
    provider: "University of Helsinki",
    imageUrl: null,
    courseUrl: "https://fullstackopen.com/en/",
    level: "intermediate",
    category: "Web Dev",
    tags: ["React", "Node.js", "MongoDB"],
    durationHours: null,
    studentCount: 500000,
    rating: 4.9,
    isFree: true,
    isPublished: true,
    order: 18,
  },
  {
    slug: "the-odin-project-foundations",
    title: "The Odin Project — Foundations",
    description: "Free, comprehensive introduction to web development with HTML, CSS, and JavaScript.",
    provider: "The Odin Project",
    imageUrl: null,
    courseUrl: "https://www.theodinproject.com/paths/foundations",
    level: "beginner",
    category: "Web Dev",
    tags: ["HTML", "CSS", "JavaScript"],
    durationHours: null,
    studentCount: 300000,
    rating: 4.9,
    isFree: true,
    isPublished: true,
    order: 19,
  },
  {
    slug: "roadmap-backend",
    title: "roadmap.sh Backend Developer Roadmap",
    description: "Comprehensive guide and roadmap for becoming a backend engineer.",
    provider: "roadmap.sh",
    imageUrl: null,
    courseUrl: "https://roadmap.sh/backend",
    level: "intermediate",
    category: "Backend",
    tags: ["Backend", "Roadmap", "Learning Path"],
    durationHours: null,
    studentCount: 1000000,
    rating: 4.7,
    isFree: true,
    isPublished: true,
    order: 20,
  },
  {
    slug: "aws-cloud-foundations",
    title: "AWS Cloud Foundations",
    description: "Introduction to AWS cloud services and cloud computing concepts.",
    provider: "AWS/AWS Skill Builder",
    imageUrl: null,
    courseUrl: "https://explore.skillbuilder.aws/learn/course/134",
    level: "beginner",
    category: "DevOps",
    tags: ["AWS", "Cloud", "DevOps"],
    durationHours: 6,
    studentCount: 1000000,
    rating: 4.7,
    isFree: true,
    isPublished: true,
    order: 21,
  },
  {
    slug: "fastai-practical-dl",
    title: "Practical Deep Learning for Coders",
    description: "Fast.ai's top-down approach to learning deep learning with PyTorch.",
    provider: "fast.ai",
    imageUrl: null,
    courseUrl: "https://course.fast.ai/",
    level: "intermediate",
    category: "AI/ML",
    tags: ["Deep Learning", "PyTorch", "Practical"],
    durationHours: null,
    studentCount: 300000,
    rating: 4.9,
    isFree: true,
    isPublished: true,
    order: 22,
  },
  {
    slug: "kaggle-intro-ml",
    title: "Intro to Machine Learning",
    description: "Kaggle's short, practical course on ML fundamentals and techniques.",
    provider: "Kaggle",
    imageUrl: null,
    courseUrl: "https://www.kaggle.com/learn/intro-to-machine-learning",
    level: "beginner",
    category: "AI/ML",
    tags: ["Machine Learning", "Kaggle", "Practical"],
    durationHours: 3,
    studentCount: 500000,
    rating: 4.7,
    isFree: true,
    isPublished: true,
    order: 23,
  },
  {
    slug: "kaggle-pandas",
    title: "Pandas",
    description: "Learn Pandas for data manipulation and analysis on Kaggle.",
    provider: "Kaggle",
    imageUrl: null,
    courseUrl: "https://www.kaggle.com/learn/pandas",
    level: "beginner",
    category: "Data",
    tags: ["Pandas", "Python", "Data Manipulation"],
    durationHours: 4,
    studentCount: 800000,
    rating: 4.8,
    isFree: true,
    isPublished: true,
    order: 24,
  },
  {
    slug: "missing-semester",
    title: "The Missing Semester of Your CS Education",
    description: "Essential tools and skills often overlooked in CS education: shell, Git, debugging, and more.",
    provider: "MIT",
    imageUrl: null,
    courseUrl: "https://missing.csail.mit.edu/",
    level: "beginner",
    category: "CS Fundamentals",
    tags: ["Tools", "Shell", "Git", "DevOps"],
    durationHours: 20,
    studentCount: 400000,
    rating: 4.9,
    isFree: true,
    isPublished: true,
    order: 25,
  },
];

async function seed() {
  const client = await pool.connect();
  try {
    console.log(`Seeding ${COURSES.length} courses...`);

    for (const course of COURSES) {
      const id = randomUUID();
      const query = `
        INSERT INTO "course" (
          "id", "slug", "title", "description", "provider", "image_url", "course_url",
          "level", "category", "tags", "duration_hours", "student_count", "rating",
          "is_free", "is_published", "order", "created_at", "updated_at"
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, NOW(), NOW()
        )
        ON CONFLICT ("slug") DO UPDATE SET
          "title" = $3, "description" = $4, "provider" = $5, "image_url" = $6,
          "course_url" = $7, "level" = $8, "category" = $9, "tags" = $10,
          "duration_hours" = $11, "student_count" = $12, "rating" = $13,
          "is_free" = $14, "is_published" = $15, "order" = $16, "updated_at" = NOW()
      `;

      const values = [
        id,
        course.slug,
        course.title,
        course.description,
        course.provider,
        course.imageUrl,
        course.courseUrl,
        course.level,
        course.category,
        JSON.stringify(course.tags),
        course.durationHours,
        course.studentCount,
        course.rating,
        course.isFree,
        course.isPublished,
        course.order,
      ];

      await client.query(query, values);
      console.log(`✓ ${course.title}`);
    }

    console.log(`\n✅ Seeded ${COURSES.length} courses successfully`);
  } catch (error) {
    console.error("Seed failed:", error);
    process.exit(1);
  } finally {
    await client.release();
    await pool.end();
  }
}

seed();
